import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-bright': '#f9f9f9',
        'on-secondary-fixed': '#001f2a',
        'primary-fixed-dim': '#b1cade',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e8e8e8',
        'on-primary': '#ffffff',
        'on-primary-container': '#c4ddf2',
        'outline-variant': '#c3c7cc',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#c9e7f7',
        secondary: '#466270',
        primary: '#324a5b',
        'inverse-surface': '#2f3131',
        'on-secondary-container': '#4a6774',
        'error-container': '#ffdad6',
        surface: '#f9f9f9',
        'on-background': '#1a1c1c',
        'on-tertiary-fixed-variant': '#5429a7',
        'on-surface': '#1a1c1c',
        'primary-container': '#4a6274',
        'surface-container-highest': '#e2e2e2',
        'surface-tint': '#496173',
        outline: '#73787c',
        'primary-fixed': '#cce6fb',
        'tertiary-fixed-dim': '#d1bcff',
        tertiary: '#552aa8',
        'on-tertiary-container': '#e2d3ff',
        'on-primary-fixed': '#021e2d',
        'inverse-primary': '#b1cade',
        'tertiary-container': '#6d46c1',
        'surface-container': '#eeeeee',
        'on-surface-variant': '#43474c',
        'inverse-on-surface': '#f1f1f1',
        'on-secondary-fixed-variant': '#2e4b57',
        'surface-container-low': '#f3f3f3',
        'on-error': '#ffffff',
        'tertiary-fixed': '#eaddff',
        'surface-variant': '#e2e2e2',
        'surface-dim': '#dadada',
        'secondary-fixed-dim': '#adcbda',
        'on-tertiary-fixed': '#24005b',
        background: '#f9f9f9',
        'secondary-container': '#c6e4f4',
        'on-primary-fixed-variant': '#31495b',
        error: '#ba1a1a',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
      },
    },
  },
} satisfies Config;
