name = "movie-filter"
main = "src/server/index.ts"
compatibility_date = "2026-03-28"

[[d1_databases]]
binding = "DB"
database_name = "movie-filter"
database_id = "00000000-0000-0000-0000-000000000000"
