name = "90sflicks"
main = "src/server/index.ts"
compatibility_date = "2026-03-28"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "movie-filter"
database_id = "da5cbb25-40a1-44cd-b39a-4b6ca75d5097"
