import type { ArchiveMovie } from '../../shared/types/archive';

export const ARCHIVE_INDEXED_COUNT = 7255;

export const archiveMovies: ArchiveMovie[] = [
  {
    id: 1,
    title: 'Pulp Fiction',
    releaseYear: 1994,
    releaseDate: '1994-10-14',
    filmType: 'movie',
    budget: 8000000,
    boxOffice: 213900000,
    genres: ['Crime', 'Drama'],
    credits: [
      { name: 'Quentin Tarantino', roleType: 'director', creditOrder: 1 },
      { name: 'Quentin Tarantino', roleType: 'writer', creditOrder: 1 },
      { name: 'Roger Avary', roleType: 'writer', creditOrder: 2 },
      { name: 'Lawrence Bender', roleType: 'producer', creditOrder: 1 },
      { name: 'John Travolta', roleType: 'cast', creditOrder: 1 },
      { name: 'Samuel L. Jackson', roleType: 'cast', creditOrder: 2 },
      { name: 'Uma Thurman', roleType: 'cast', creditOrder: 3 },
      { name: 'Bruce Willis', roleType: 'cast', creditOrder: 4 },
    ],
    companies: [
      { name: 'Miramax Films', roleType: 'distribution' },
      { name: 'A Band Apart', roleType: 'production' },
      { name: 'Jersey Films', roleType: 'production' },
    ],
  },
  {
    id: 2,
    title: 'The Matrix',
    releaseYear: 1999,
    releaseDate: '1999-03-31',
    filmType: 'movie',
    budget: 63000000,
    boxOffice: 463517383,
    genres: ['Sci-Fi', 'Action'],
    credits: [
      { name: 'Lana Wachowski', roleType: 'director', creditOrder: 1 },
      { name: 'Lilly Wachowski', roleType: 'director', creditOrder: 2 },
      { name: 'Lana Wachowski', roleType: 'writer', creditOrder: 1 },
      { name: 'Lilly Wachowski', roleType: 'writer', creditOrder: 2 },
      { name: 'Joel Silver', roleType: 'producer', creditOrder: 1 },
      { name: 'Keanu Reeves', roleType: 'cast', creditOrder: 1 },
      { name: 'Laurence Fishburne', roleType: 'cast', creditOrder: 2 },
      { name: 'Carrie-Anne Moss', roleType: 'cast', creditOrder: 3 },
      { name: 'Hugo Weaving', roleType: 'cast', creditOrder: 4 },
    ],
    companies: [
      { name: 'Warner Bros.', roleType: 'distribution' },
      { name: 'Village Roadshow Pictures', roleType: 'production' },
      { name: 'Silver Pictures', roleType: 'production' },
    ],
  },
  {
    id: 3,
    title: 'Goodfellas',
    releaseYear: 1990,
    releaseDate: '1990-09-19',
    filmType: 'movie',
    budget: 25000000,
    boxOffice: 46800000,
    genres: ['Crime', 'Biography'],
    credits: [
      { name: 'Martin Scorsese', roleType: 'director', creditOrder: 1 },
      { name: 'Nicholas Pileggi', roleType: 'writer', creditOrder: 1 },
      { name: 'Martin Scorsese', roleType: 'writer', creditOrder: 2 },
      { name: 'Irwin Winkler', roleType: 'producer', creditOrder: 1 },
      { name: 'Robert De Niro', roleType: 'cast', creditOrder: 1 },
      { name: 'Ray Liotta', roleType: 'cast', creditOrder: 2 },
      { name: 'Joe Pesci', roleType: 'cast', creditOrder: 3 },
      { name: 'Lorraine Bracco', roleType: 'cast', creditOrder: 4 },
    ],
    companies: [
      { name: 'Warner Bros.', roleType: 'distribution' },
      { name: 'Winkler Films', roleType: 'production' },
    ],
  },
  {
    id: 4,
    title: 'Heat',
    releaseYear: 1995,
    releaseDate: '1995-12-15',
    filmType: 'movie',
    budget: 60000000,
    boxOffice: 187400000,
    genres: ['Crime', 'Drama', 'Thriller'],
    credits: [
      { name: 'Michael Mann', roleType: 'director', creditOrder: 1 },
      { name: 'Michael Mann', roleType: 'writer', creditOrder: 1 },
      { name: 'Art Linson', roleType: 'producer', creditOrder: 1 },
      { name: 'Robert De Niro', roleType: 'cast', creditOrder: 1 },
      { name: 'Al Pacino', roleType: 'cast', creditOrder: 2 },
      { name: 'Val Kilmer', roleType: 'cast', creditOrder: 3 },
      { name: 'Jon Voight', roleType: 'cast', creditOrder: 4 },
    ],
    companies: [
      { name: 'Warner Bros.', roleType: 'distribution' },
      { name: 'Regency Enterprises', roleType: 'production' },
      { name: 'Forward Pass', roleType: 'production' },
    ],
  },
  {
    id: 5,
    title: 'Se7en',
    releaseYear: 1995,
    releaseDate: '1995-09-22',
    filmType: 'movie',
    budget: 33000000,
    boxOffice: 327300000,
    genres: ['Crime', 'Drama', 'Thriller'],
    credits: [
      { name: 'David Fincher', roleType: 'director', creditOrder: 1 },
      { name: 'Andrew Kevin Walker', roleType: 'writer', creditOrder: 1 },
      { name: 'Arnold Kopelson', roleType: 'producer', creditOrder: 1 },
      { name: 'Brad Pitt', roleType: 'cast', creditOrder: 1 },
      { name: 'Morgan Freeman', roleType: 'cast', creditOrder: 2 },
      { name: 'Gwyneth Paltrow', roleType: 'cast', creditOrder: 3 },
      { name: 'Kevin Spacey', roleType: 'cast', creditOrder: 4 },
    ],
    companies: [
      { name: 'New Line Cinema', roleType: 'distribution' },
      { name: 'Cecchi Gori Pictures', roleType: 'production' },
    ],
  },
];
